### ISSUE TITLE
Marionette.Application has no addInitializer method

### ISSUE THREAD

**Issue by codetodamoon** [dmytroyarmak/marionette-contact-manager#1]
Marionette.Application has no addInitializer method and Marionette has no Controlller
have i user the wrong version of Marionette。
the version i use is v3.0.0

**Comment by dmytroyarmak** [comment]
Hi @lixuejiang 
Yes, you are right. This tutorial was written on Marionette v1.6.1
I haven't used Marionette for the last two years, so I'm not sure what is an alternative in the current version.

**Comment by codetodamoon** [comment]
@dmytroyarmak i see,anyway thank you very much,are you still use backbone for your application development

**Comment by dmytroyarmak** [comment]
@lixuejiang No, for the last two years I'm using Angular 1.x at work and currently playing with React and Angular 2 in the spare time

**Comment by codetodamoon** [comment]
so awesome
